[APP]
APP_NAME = "ChatHere"
VERSION = "V1.1"
AUTHOR = "XLY23333"

[MODEL.OLLAMA.Qwen-3-8B-OLLAMA]
URL = "http://localhost:11434/api/chat"
ID = "qwen3:8b"

[MODEL.OLLAMA.DeepSeek-R1-8B-OLLAMA]
URL = "http://localhost:11434/api/chat"
ID = "deepseek-r1:8b"

[MODEL.OLLAMA.Gemma-3-12B-OLLAMA]
URL = "http://localhost:11434/api/chat"
ID = "gemma3:12b"

[MODEL.OLLAMA.LLAMA-3dot1-8B-OLLAMA]
URL = "http://localhost:11434/api/chat"
ID = "llama3.1:8b "

[MODEL.CA.GPT-4dot1-mini]
URL = "https://api.chatanywhere.tech"
ID = "gpt-4.1-mini"

[MODEL.CA.GPT-4o-mini]
URL = "https://api.chatanywhere.tech"
ID = "gpt-4o-mini"

[MODEL.CA.DeepSeek-R1]
URL = "https://api.chatanywhere.tech"
ID = "deepseek-r1"

[MODEL.CA.DeepSeek-V3]
URL = "https://api.chatanywhere.tech"
ID = "deepseek-v3"


[MODEL.SF.DS-R1-FULL]
URL = "https://api.siliconflow.cn/v1"
ID = "deepseek-ai/DeepSeek-R1"

[MODEL.SF.DS-V3]
URL = "https://api.siliconflow.cn/v1"
ID = "deepseek-ai/DeepSeek-V3"

[MODEL.SF.Qwen3-235B-A22B]
URL = "https://api.siliconflow.cn/v1"
ID = "Qwen/Qwen3-235B-A22B"